#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import print_function
import boxbranding
print("getOEVersion=%s<" %boxbranding.getOEVersion())
print("getImageDistro=%s<" %boxbranding.getImageDistro())
print("getBoxType=%s<" %boxbranding.getBoxType())
print("getBrandOEM=%s<" %boxbranding.getBrandOEM())
print("getMachineBrand=%s<" %boxbranding.getMachineBrand())
print("getMachineName=%s<" %boxbranding.getMachineName())
print("getMachineBuild=%s<" %boxbranding.getMachineBuild())
print("getMachineMake=%s<" %boxbranding.getMachineMake())
print("getImageVersion=%s<" %boxbranding.getImageVersion())
print("getImageBuild=%s<" %boxbranding.getImageBuild())
print("getImageDevBuild=%s<" %boxbranding.getImageDevBuild())
print("getImageType=%s<" %boxbranding.getImageType())
print("getFeedsUrl=%s<" %boxbranding.getFeedsUrl())
print("getImageFolder=%s<" %boxbranding.getImageFolder())
print("getImageFileSystem=%s<" %boxbranding.getImageFileSystem())
print("getMachineMtdBoot=%s<" %boxbranding.getMachineMtdBoot())
print("getMachineMtdRoot=%s<" %boxbranding.getMachineMtdRoot())
print("getMachineMtdKernel=%s<" %boxbranding.getMachineMtdKernel())
print("getMachineRootFile=%s<" %boxbranding.getMachineRootFile())
print("getMachineKernelFile=%s<" %boxbranding.getMachineKernelFile())
print("getMachineMKUBIFS=%s<" %boxbranding.getMachineMKUBIFS())
print("getMachineUBINIZE=%s<" %boxbranding.getMachineUBINIZE())
print("getImageArch=%s<" %boxbranding.getImageArch())
print("getHaveTranscoding=%s<" %boxbranding.getHaveTranscoding())
print("getHaveMultiTranscoding=%s<" %boxbranding.getHaveMultiTranscoding())
print("getMachineProcModel=%s<" %boxbranding.getMachineProcModel())
